// @codekit-prepend "vendor/jquery-2.1.3.min.js";
// @codekit-prepend "vendor/angular.min.js";
// @codekit-prepend "vendor/nlp_compromise.min.js";
// @codekit-prepend "vendor/responsivevoice.js";
// @codekit-prepend "vendor/handlebars-v3.0.3.js";
// @codekit-prepend "bootstrap.min.js";
// @codekit-prepend "nlp_compromise.js";
// @codekit-prepend "speechInput.js";
// @codekit-prepend "mappedCartItems.js";
// @codekit-prepend "outputModel.js";
// @codekit-prepend "cartItems.js"
// @codekit-prepend "levenshtein.js"
// @codekit-prepend "dataParser.js";
// @codekit-prepend "app.js";
// @codekit-prepend "common.js";
// @codekit-prepend "dialog.js";
